/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.platform.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.platform.PlatformEvent;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.platform.PlatformAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlatformActionValidator {
	boolean validate();

	boolean validateKind(String value);
	boolean validatePlatformElement(EList<PlatformEvent> value);
}
