/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.conceptual.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.action.ActionElement;

import org.eclipse.gmt.modisco.omg.kdm.conceptual.AbstractConceptualRelationship;

import org.eclipse.gmt.modisco.omg.kdm.source.SourceRef;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.conceptual.AbstractConceptualElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractConceptualElementValidator {
	boolean validate();

	boolean validateSource(EList<SourceRef> value);
	boolean validateConceptualRelation(EList<AbstractConceptualRelationship> value);
	boolean validateAbstraction(EList<ActionElement> value);
}
