/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.source.validation;

import org.eclipse.gmt.modisco.omg.kdm.source.SourceFile;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.source.SourceRegion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SourceRegionValidator {
	boolean validate();

	boolean validateFile(SourceFile value);
	boolean validateStartLine(Integer value);
	boolean validateStartPosition(Integer value);
	boolean validateEndLine(Integer value);
	boolean validateEndPosition(Integer value);
	boolean validateLanguage(String value);
	boolean validatePath(String value);
}
