/**
 *
 * $Id$
 */
package series.validation;

import org.eclipse.emf.common.util.EList;

import series.Categoria;

/**
 * A sample validator interface for {@link series.EjeX}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EjeXValidator {
	boolean validate();

	boolean validateEjeXCategoria(EList<Categoria> value);
	boolean validateName(String value);
}
