/**
 *
 * $Id$
 */
package series.validation;

import org.eclipse.emf.common.util.EList;

import series.EjeX;
import series.EjeY;
import series.Serie;
import series.TipoGrafica;

/**
 * A sample validator interface for {@link series.Grafica}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GraficaValidator {
	boolean validate();

	boolean validateTitulo(String value);
	boolean validateSubtitulo(String value);
	boolean validateTipo(TipoGrafica value);
	boolean validateGraficaSerie(EList<Serie> value);
	boolean validateGraficaEjeX(EList<EjeX> value);
	boolean validateGraficaEjeY(EList<EjeY> value);
}
