/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.structure.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.core.AggregatedRelationship;

import org.eclipse.gmt.modisco.omg.kdm.structure.AbstractStructureElement;
import org.eclipse.gmt.modisco.omg.kdm.structure.AbstractStructureRelationship;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.structure.AbstractStructureElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractStructureElementValidator {
	boolean validate();

	boolean validateAggregated(EList<AggregatedRelationship> value);
	boolean validateStructureElement(EList<AbstractStructureElement> value);
	boolean validateStructureRelationship(EList<AbstractStructureRelationship> value);
}
