/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.event.validation;

import org.eclipse.gmt.modisco.omg.kdm.event.Event;
import org.eclipse.gmt.modisco.omg.kdm.event.Transition;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.event.ConsumesEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConsumesEventValidator {
	boolean validate();

	boolean validateTo(Event value);
	boolean validateFrom(Transition value);
}
