/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.event.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.event.AbstractEventElement;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.event.EventResource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventResourceValidator {
	boolean validate();

	boolean validateEventElement(EList<AbstractEventElement> value);
}
