/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.core.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.core.KDMRelationship;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.core.AggregatedRelationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AggregatedRelationshipValidator {
	boolean validate();

	boolean validateRelation(EList<KDMRelationship> value);
	boolean validateDensity(Integer value);
}
