/**
 *
 * $Id$
 */
package org.eclipse.gmt.modisco.omg.kdm.ui.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.modisco.omg.kdm.action.ActionElement;

import org.eclipse.gmt.modisco.omg.kdm.code.AbstractCodeElement;

import org.eclipse.gmt.modisco.omg.kdm.source.SourceRef;

import org.eclipse.gmt.modisco.omg.kdm.ui.AbstractUIRelationship;

/**
 * A sample validator interface for {@link org.eclipse.gmt.modisco.omg.kdm.ui.AbstractUIElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractUIElementValidator {
	boolean validate();

	boolean validateSource(EList<SourceRef> value);
	boolean validateUIRelation(EList<AbstractUIRelationship> value);
	boolean validateImplementation(EList<AbstractCodeElement> value);
	boolean validateAbstraction(EList<ActionElement> value);
}
